# Generated by Django 5.1.5 on 2025-02-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card_items',
            new_name='cart_items',
        ),
    ]
